name: Cycle
description: Creates simple image cycle widgets for emedding into your site that contain image, description, and links.

author: Tom Maiaroto
authorEmail: tom@shift8creative.com
authorUrl: http://www.shift8creative.com
